linters:
  enable:
    - goconst
    - gocritic
    - gofmt
    - govet
    - prealloc
    - unconvert
    - deadcode
    - structcheck
    - varcheck
    - errcheck
    - ineffassign
    - typecheck
    - containedctx
    - tenv
