linters:
  enable:
    - goconst
    - gocritic
    - gofmt
    - govet
    - prealloc
    - unconvert
    - unused
    - errcheck
    - ineffassign
    - containedctx
    - tenv
    - musttag
    - mirror
    - tagalign
    - zerologlint

run:
  go: '1.21'
  timeout: 3m
