linters:
  enable:
    - goconst
    - gocritic
    - gofmt
    - govet
    - prealloc
    - unconvert
    - unused
    - errcheck
    - ineffassign
    - containedctx
    - tenv

run:
  go: '1.19'
  timeout: 3m
