language: go

go:
  - 1.13.x

services:
  - docker

stages:
  - name: test
    if: tag IS blank

jobs:
  include:
    - stage: test
      script:
        - export GO111MODULE=on
        - go mod download
        - go test -v ./...
        - touch .env
        - docker-compose build
