language: go

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      script:
        - go mod download
        - go test -v ./...
        - touch .env
        - docker-compose build
    - stage: deploy
      services:
        - docker
      script:
        - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
        - touch .env
        - export TAG=${TRAVIS_TAG}
        - docker-compose build
        - docker-compose push
