version: "3.6"
services:
  api:
    volumes:
      - /etc/bcd:/etc/bcd
      - ./cmd/api/config.json:/app/api/config.json

  indexer:
    volumes:
      - /etc/bcd:/etc/bcd
      - ./cmd/indexer/config.json:/app/indexer/config.json

  metrics:
    volumes:
      - ./cmd/metrics/config.json:/app/metrics/config.json
