version: "3.6"
services:
  elastic:
    ports:
      - "127.0.0.1:9308:9300"
      - "127.0.0.1:9208:9200"

  mq:
    ports:
      - "127.0.0.1:15678:15672"
      - "127.0.0.1:5678:5672"    

  db:
    ports:
      - 127.0.0.1:5438:5432

  compiler-dev:
    container_name: bcd-compiler-dev
    restart: always
    image: bakingbad/bcdhub-compiler-dev:${TAG:-latest}
    build:
      context: .
      dockerfile: cmd/compiler/Dockerfile.dev
    env_file:
      - .env
    depends_on:
      - elastic
      - mq
      - db
    volumes:
      - ${HOME}/.bcd:${HOME}/.bcd
    logging: &my-logging
      options:
        max-size: 10m
        max-file: "5"
