version: "3.6"
services:
  elastic:
    image: ghcr.io/baking-bad/bcdhub-elastic:${TAG}
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"  # CHANGEME: ElasticSearch RAM comsumption
    logging: &bcd-logging
      options:
        max-size: 10m
        max-file: "5"

  db:
    image: postgres:14
    shm_size: 1g
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=indexer
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    logging: *bcd-logging

  api:
    restart: always
    image: ghcr.io/baking-bad/bcdhub-api:${TAG}
    environment:
      - BCD_ENV=production
      - GIN_MODE=release
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PAGE_SIZE=100
      - SANDBOX_IPFS_GATEWAY=https://cloudflare-ipfs.com
    depends_on:
      - elastic
      - db
    ports:
      - 127.0.0.1:14000:14000
    volumes:
      - bcdshare:/etc/bcd
    logging: *bcd-logging

  indexer:
    restart: always
    image: ghcr.io/baking-bad/bcdhub-indexer:${TAG}
    environment:
      - BCD_ENV=production
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SANDBOX_IPFS_GATEWAY=https://cloudflare-ipfs.com
    depends_on:
      - elastic
      - metrics
    volumes:
      - bcdshare:/etc/bcd
    logging: *bcd-logging

  metrics:
    restart: always
    image: ghcr.io/baking-bad/bcdhub-metrics:${TAG}
    environment:
      - BCD_ENV=production
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SANDBOX_IPFS_GATEWAY=https://cloudflare-ipfs.com
    depends_on:
      - elastic
      - db
    volumes:
      - bcdshare:/etc/bcd
    logging: *bcd-logging

volumes:
  esdata:
  bcdshare:
  db:
    driver: local
