version: "3.6"
services:
  elastic:
    image: bakingbad/bcdhub-elastic:${TAG:-latest}
    build:
      context: .
      dockerfile: build/elastic/Dockerfile
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    env_file:
      - .env
    ports:
      - "127.0.0.1:${ES_REQUESTS_PORT}:9200"
    logging: &bcd-logging
      options:
        max-size: 10m
        max-file: "5"

  db:
    image: bakingbad/bcdhub-db:${TAG:-latest}
    shm_size: 1g
    build:
      context: .
      dockerfile: build/db/Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:5432
    logging: *bcd-logging
    command:
      - "postgres"
      - "-c"
      - "config_file=${POSTGRES_CONFIG:-/var/lib/postgresql/data/postgresql.conf}"

  api:
    restart: always
    image: bakingbad/bcdhub-api:${TAG:-latest}
    build:
      context: .
      dockerfile: build/api/Dockerfile
    env_file:
      - .env
    depends_on:
      - elastic
      - db
    ports:
      - 127.0.0.1:${BCD_API_PORT}:14000
    volumes:
      - ${SHARE_PATH}:/etc/bcd
    logging: *bcd-logging

  indexer:
    restart: always
    image: bakingbad/bcdhub-indexer:${TAG:-latest}
    build:
      context: .
      dockerfile: build/indexer/Dockerfile
    env_file:
      - .env
    depends_on:
      - elastic
      - metrics
    volumes:
      - ${SHARE_PATH}:/etc/bcd
    logging: *bcd-logging

  metrics:
    restart: always
    image: bakingbad/bcdhub-metrics:${TAG:-latest}
    build:
      context: .
      dockerfile: build/metrics/Dockerfile
    env_file:
      - .env
    depends_on:
      - elastic
      - db
    volumes:
      - ${SHARE_PATH}:/etc/bcd
    logging: *bcd-logging

  gui:
    restart: always
    image: bakingbad/bcdhub-gui:${TAG:-latest}
    entrypoint: /bin/bash
    command: >-
      -c "(cp /etc/bcd/nginx/default.${BCD_ENV:-production}.conf /etc/nginx/conf.d/default.conf || true)
      && (cp /etc/bcd/nginx/sitemap.${BCD_ENV:-production}.xml /usr/share/nginx/html/sitemap.xml || true)
      && nginx -g 'daemon off;'"
    ports:
      - 127.0.0.1:${BCD_GUI_PORT}:80
    volumes:
      - ${SHARE_PATH}:/etc/bcd
    logging: *bcd-logging

#  graphql:
#    restart: always
#    image: bakingbad/bcdhub-graphql:${TAG:-latest}
#    build:
#      context: .
#      dockerfile: build/graphql/Dockerfile
#    env_file:
#      - .env
#    depends_on:
#      - db
#    ports:
#      - 127.0.0.1:3000:3000
#    volumes:
#      - ${SHARE_PATH}:/etc/bcd
#    logging: *bcd-logging

volumes:
  esdata:
  db:
    driver: local
