version: "3.6"
services:
  elastic:
    image: bakingbad/bcdhub-elastic:${TAG}
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    logging: &bcd-logging
      options:
        max-size: 10m
        max-file: "5"

  mq:
    image: rabbitmq:latest
    restart: always
    volumes:
      - mqdata:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    logging: *bcd-logging

  db:
    image: bakingbad/bcdhub-db:${TAG:-latest}
    build:
      context: .
      dockerfile: build/db/Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd_box
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    logging: *bcd-logging

  api:
    restart: always
    image: bakingbad/bcdhub-api:${TAG}
    environment:
      - BCD_ENV=sandbox
      - GIN_MODE=debug
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd_box
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - SANDBOX_NODE_URI=http://sandbox:8732
      - SANDBOX_IPFS_GATEWAY=https://cloudflare-ipfs.com
    depends_on:
      - elastic
      - db
      - mq
    ports:
      - 127.0.0.1:14000:14000
    volumes:
      - bcdshare:/etc/bcd
    extra_hosts:
      sandbox: 172.17.0.1
    logging: *bcd-logging

  indexer:
    restart: always
    image: bakingbad/bcdhub-indexer:${TAG}
    environment:
      - BCD_ENV=sandbox
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd_box
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - SANDBOX_NODE_URI=http://sandbox:8732
      - SANDBOX_IPFS_GATEWAY=https://cloudflare-ipfs.com
    depends_on:
      - db
      - mq
      - metrics
    extra_hosts:
      sandbox: 172.17.0.1
    volumes:
      - bcdshare:/etc/bcd
    logging: *bcd-logging

  metrics:
    restart: always
    image: bakingbad/bcdhub-metrics:${TAG}
    environment:
      - BCD_ENV=sandbox
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd_box
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - SANDBOX_NODE_URI=http://sandbox:8732
      - SANDBOX_IPFS_GATEWAY=https://cloudflare-ipfs.com
    depends_on:
      - elastic
      - mq
      - db
    extra_hosts:
      sandbox: 172.17.0.1
    volumes:
      - bcdshare:/etc/bcd
    logging: *bcd-logging

  flextesa:
    restart: always
    image: trufflesuite/flextesa-mini-archive
    command: edobox start
    environment:
      - block_time=4
    ports:
      - 127.0.0.1:8732:20000
      - 172.17.0.1:8732:20000
    logging: *bcd-logging

  #  jupyter:
  #    container_name: sandbox-jupyter
  #    restart: always
  #    image: bakingbad/bcdhub-jupyter:${TAG:-latest}
  #    build:
  #      context: .
  #      dockerfile: build/sandbox/jupyter/Dockerfile
  #    ports:
  #      - 127.0.0.1:8008:8008
  #    extra_hosts:
  #      sandbox: 172.17.0.1
  #    logging: *bcd-logging

  gui:
    container_name: sandbox-gui
    restart: always
    image: bakingbad/bcdhub-gui:${TAG}
    depends_on:
      - api
    ports:
      - 127.0.0.1:8000:80
    logging: *bcd-logging

volumes:
  esdata:
  mqdata:
  bcdshare:
  db:
    driver: local
