version: "3.6"
services:
  elastic:
    container_name: bcd-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
    logging: &my-logging
      options:
        max-size: 10m
        max-file: "5"

  mq:
    container_name: bcd-mq
    image: rabbitmq:latest
    restart: always
    volumes:
      - mqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    logging: *my-logging        

  db:
    container_name: bcd-db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    logging: *my-logging

  api:
    container_name: bcd-api
    restart: always
    image: registry.github.com/aopoltorzhicky/bcdhub/api
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    env_file:
      - .env
    depends_on:
      - elastic
      - db
    volumes:
      - /etc/bcd:/etc/bcd
    ports:
      - 127.0.0.1:14000:14000
    logging: *my-logging

  indexer:
    container_name: bcd-indexer
    restart: always
    image: registry.github.com/aopoltorzhicky/bcdhub/indexer
    build:
      context: .
      dockerfile: cmd/indexer/Dockerfile
    env_file:
      - .env
    volumes:
      - /etc/bcd:/etc/bcd
    depends_on:
      - elastic
      - mq
    logging: *my-logging

  opindexer:
    container_name: bcd-opindexer
    restart: always
    image: registry.github.com/aopoltorzhicky/bcdhub/opindexer
    build:
      context: .
      dockerfile: cmd/operation_indexer/Dockerfile
    env_file:
      - .env
    depends_on:
      - elastic
      - mq
    logging: *my-logging

  metrics:
    container_name: bcd-metrics
    restart: always
    image: registry.github.com/aopoltorzhicky/bcdhub/metrics
    build:
      context: .
      dockerfile: cmd/metrics/Dockerfile
    env_file:
      - .env
    depends_on:
      - elastic
      - mq
    logging: *my-logging

volumes:
  esdata:
  mqdata:
  db:
    driver: local
