version: "3.6"
services:
  compiler-dev:
    container_name: bcd-compiler-dev
    restart: always
    image: bakingbad/bcdhub-compiler-dev:${TAG:-latest}
    build:
      context: .
      dockerfile: cmd/compiler/Dockerfile.dev
    env_file:
      - .env
    depends_on:
      - elastic
      - mq
      - db
    volumes:
      - ${HOME}/.bcd:${HOME}/.bcd
    logging: &my-logging
      options:
        max-size: 10m
        max-file: "5"
