rpc:
    sandboxnet:
        uri: http://sandbox:8732
        timeout: 10

seed:
    user:
        login: sandboxuser
        name: "Default User"
        avatar_url: "https://services.tzkt.io/v1/avatars/bcd"
        token: ""
    subscriptions:
        - address: tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
          network: sandboxnet
          alias: Alice
          watch_mask: 127
        - address: tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6
          network: sandboxnet
          alias: Bob
          watch_mask: 127
    aliases:
        - alias: Alice
          network: sandboxnet
          address: tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
        - alias: Bob
          network: sandboxnet
          address: tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6
    accounts:
        - private_key: "privatekey"
          public_key_hash: "publickeyhash"
          network: "sandboxnet"

api:
    project_name: api
    bind: ":14000"
    swagger_host: "localhost:42000"
    cors_enabled: true
    oauth:
        enabled: false
    sentry:
        enabled: false
    networks:
        - sandboxnet
    seed:
        enabled: true
    queues:
        operations:
            non_durable: true
            auto_deleted: true
