rpc:
    mainnet:
        uri: https://rpc.tzkt.io/mainnet
        timeout: 20
    delphinet:
        uri: https://rpc.tzkt.io/delphinet
        timeout: 20
    dalphanet:
        uri: https://rpc.tzkt.io/dalphanet
        timeout: 20
    carthagenet:
        uri: https://rpc.tzkt.io/carthagenet
        timeout: 20

tzkt:
    mainnet:
        uri: https://api.tzkt.io/v1/
        services_uri: https://services.tzkt.io/v1/
        timeout: 20
    delphinet:
        uri: https://api.delphi.tzkt.io/v1/
        services_uri: https://services.tzkt.io/delphinet/v1/
        timeout: 20
    carthagenet:
        uri: https://api.carthage.tzkt.io/v1/
        services_uri: https://services.tzkt.io/carthagenet/v1/
        timeout: 20

share:
    path: /etc/bcd

sentry:
    environment: production
    uri: ${SENTRY_DSN}
    debug: false

elastic:
    uri: http://elastic:9200
    timeout: 10

db:
    conn_string: "host=db port=5432 user=${POSTGRES_USER} dbname=${POSTGRES_DB} password=${POSTGRES_PASSWORD} sslmode=disable"

oauth:
    state: ${OAUTH_STATE_STRING}
    jwt:
        secret: ${JWT_SECRET_KEY}
        redirect_url: https://better-call.dev/welcome
    github:
        client_id: ${GITHUB_CLIENT_ID}
        secret: ${GITHUB_CLIENT_SECRET}
        callback_url: https://api.better-call.dev/v1/oauth/github/callback
    gitlab:
        client_id: ${GITLAB_CLIENT_ID}
        secret: ${GITLAB_CLIENT_SECRET}
        callback_url: https://api.better-call.dev/v1/oauth/gitlab/callback

api:
    bind: ":14000"
    swagger_host: "api.better-call.dev"
    oauth:
        enabled: true
    sentry:
        enabled: true
        project: api
    networks:
        - mainnet
        - carthagenet
        - delphinet
        - dalphanet
    seed:
        enabled: false

rabbitmq:
    uri: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@mq:5672/"
    queues:
        - operations

aws:
  bucket_name: bcd-elastic-snapshots
  region: eu-central-1

migrations:
    networks:
        - mainnet
        - carthagenet
        - delphinet
        - dalphanet
