rpc:
  mainnet:
    uri: https://rpc.tzkt.io/mainnet
    timeout: 20
  edo2net:
    uri: https://rpc.tzkt.io/edo2net
    timeout: 20
  florencenet:
    uri: https://rpc.tzkt.io/florencenobanet
    timeout: 20
  granadanet:
    uri: https://granadanet.smartpy.io/
    timeout: 20

tzkt:
  mainnet:
    uri: https://api.tzkt.io/v1/
    services_uri: https://services.tzkt.io/v1/
    base_uri: https://tzkt.io/
    timeout: 20
  edo2net:
    uri: https://api.edo2net.tzkt.io/v1/
    services_uri: https://services.tzkt.io/edo2net/v1/
    base_uri: https://edo2net.tzkt.io/
    timeout: 20
  florencenet:
    uri: https://api.florencenet.tzkt.io/v1/
    services_uri: https://services.tzkt.io/florencenet/v1/
    base_uri: https://florencenet.tzkt.io/
    timeout: 20

storage:
  pg: "host=${DB_HOSTNAME:-127.0.0.1} port=5432 user=${POSTGRES_USER} dbname=indexer password=${POSTGRES_PASSWORD} sslmode=disable"
  elastic:
    - http://${ELASTIC_HOSTNAME:-127.0.0.1}:9200
  timeout: 10

sentry:
  environment: development
  uri: ${SENTRY_DSN}
  front_uri: ${SENTRY_DSN_FRONT}
  debug: true

share_path: /etc/bcd

base_url: http://localhost:8080

ipfs:
  - https://cloudflare-ipfs.com
  - https://ipfs.io
  - https://dweb.link

domains:
  edo2net: KT1KP2Yy6MNkYKkHqroGBZ7KFN5NdNfnUHHv
  mainnet: KT1GBZmSxmnKJXGMdMLbugPfLyUPmuLSMwKS

api:
  project_name: api
  bind: "127.0.0.1:14000"
  swagger_host: "localhost:14000"
  cors_enabled: true
  sentry_enabled: false
  seed_enabled: false
  page_size: ${PAGE_SIZE:-10}
  frontend:
    ga_enabled: false
    mempool_enabled: true
    sandbox_mode: false
  networks:
    - mainnet
    - edo2net
    - florencenet
    - granadanet
  pinata:
    key: ${PINATA_KEY}
    secret_key: ${PINATA_SECRET_KEY}
    timeout_seconds: 10
  connections:
    max: 50
    idle: 50

indexer:
  project_name: indexer
  sentry_enabled: false
  skip_delegator_blocks: true
  networks:
    mainnet:
      boost: tzkt
    edo2net:
      boost: tzkt
    florencenet:
    granadanet:
  connections:
    max: 5
    idle: 5

metrics:
  project_name: metrics
  sentry_enabled: false
  cache_aliases_seconds: 30
  connections:
    max: 10
    idle: 10

scripts:
  aws:
    bucket_name: bcd-elastic-snapshots
    region: eu-central-1
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  networks:
    - mainnet
    - edo2net
    - florencenet
    - granadanet
  connections:
    max: 5
    idle: 5

graphql:
  db: "host=127.0.0.1 port=5432 user=graphql dbname=indexer password=${POSTGRES_GRAPHQL} sslmode=disable"