rpc:
  mainnet:
    uri: https://rpc.tzkt.io/archive
    timeout: 20
    requests_per_second: 15
  ghostnet:
    uri: https://rpc.tzkt.io/ghostnet
    timeout: 20
    requests_per_second: 10
  limanet:
    uri: https://rpc.tzkt.io/limanet
    timeout: 20
    requests_per_second: 20

tzkt:
  mainnet:
    uri: https://api.tzkt.io/v1

services:
  mainnet:
    mempool: https://mempool.dipdup.net/v1/graphql
  ghostnet:
    mempool: https://mempool.test.dipdup.net/v1/graphql
  limanet:
    mempool: https://mempool.test.dipdup.net/v1/graphql

storage:
  pg: 
    host: ${DB_HOSTNAME:-127.0.0.1}
    port: 5432
    user: ${POSTGRES_USER}
    dbname: ${POSTGRES_DB:-bcd}
    password: ${POSTGRES_PASSWORD}
    sslmode: disable
  timeout: 10

sentry:
  environment: development
  uri: ${SENTRY_DSN}
  front_uri: ${SENTRY_DSN_FRONT}
  debug: true

share_path: /etc/bcd

base_url: http://localhost:8080

api:
  project_name: api
  bind: "127.0.0.1:14000"
  swagger_host: "localhost:14000"
  cors_enabled: true
  sentry_enabled: false
  seed_enabled: false
  page_size: ${PAGE_SIZE:-10}
  frontend:
    ga_enabled: false
    mempool_enabled: true
    sandbox_mode: false
    rpc:
      mainnet: https://rpc.tzkt.io/mainnet
      ghostnet: https://rpc.tzkt.io/ghostnet
      limanet: https://rpc.tzkt.io/limanet
  networks:
    - mainnet
    - ghostnet
    - limanet
  connections:
    max: 50
    idle: 50

indexer:
  project_name: indexer
  sentry_enabled: false
  networks:
    mainnet:
      receiver_threads: 5
    ghostnet:
      receiver_threads: 10
    limanet:
      receiver_threads: 10
  connections:
    max: 5
    idle: 5

scripts:
  aws:
    bucket_name: bcd-elastic-snapshots
    region: eu-central-1
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  networks:
    - mainnet
    - ghostnet
    - limanet
  connections:
    max: 5
    idle: 5