rpc:
  mainnet:
    uri: https://rpc.tzkt.io/mainnet
    timeout: 20
  hangzhou2net:
    uri: https://rpc.tzkt.io/hangzhou2net
    timeout: 20
  ithacanet:
    uri: https://rpc.tzkt.io/ithacanet
    timeout: 20

services:
  mainnet:
    mempool: https://mempool.dipdup.net/v1/graphql
  granadanet:
    mempool: https://mempool.dipdup.net/v1/graphql
  hangzhou2net:
    mempool: https://mempool.dipdup.net/v1/graphql

storage:
  pg: "host=${DB_HOSTNAME:-127.0.0.1} port=5432 user=${POSTGRES_USER} dbname=${POSTGRES_DB:-indexer} password=${POSTGRES_PASSWORD} sslmode=disable"
  elastic:
    - http://${ELASTIC_HOSTNAME:-127.0.0.1}:9200
  timeout: 10

sentry:
  environment: development
  uri: ${SENTRY_DSN}
  front_uri: ${SENTRY_DSN_FRONT}
  debug: true

share_path: /etc/bcd

base_url: http://localhost:8080

ipfs:
  - https://cloudflare-ipfs.com
  - https://ipfs.io
  - https://dweb.link

domains:
  mainnet: KT1GBZmSxmnKJXGMdMLbugPfLyUPmuLSMwKS

api:
  project_name: api
  bind: "127.0.0.1:14000"
  swagger_host: "localhost:14000"
  cors_enabled: true
  sentry_enabled: false
  seed_enabled: false
  page_size: ${PAGE_SIZE:-10}
  frontend:
    ga_enabled: false
    mempool_enabled: true
    sandbox_mode: false
    rpc:
      mainnet: https://rpc.tzkt.io/mainnet
      hangzhou2net: https://rpc.tzkt.io/hangzhou2net
  networks:
    - mainnet
    - hangzhou2net
    - ithacanet
  connections:
    max: 50
    idle: 50

indexer:
  project_name: indexer
  sentry_enabled: false
  skip_delegator_blocks: true
  networks:
    mainnet:
    hangzhou2net:
    ithacanet:
  connections:
    max: 5
    idle: 5

metrics:
  project_name: metrics
  sentry_enabled: false
  cache_aliases_seconds: 30
  connections:
    max: 10
    idle: 10

scripts:
  aws:
    bucket_name: bcd-elastic-snapshots
    region: eu-central-1
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  networks:
    - mainnet
    - hangzhou2net
    - ithacanet
  connections:
    max: 5
    idle: 5
