rpc:
  mainnet:
    uri: ${MAINNET_RPC_URI:-https://rpc.tzkt.io/mainnet}
    timeout: 20
    requests_per_second: 15
  ghostnet:
    uri: https://rpc.tzkt.io/ghostnet
    timeout: 20
    requests_per_second: 10
  jakartanet:
    uri: https://rpc.tzkt.io/jakartanet
    timeout: 20
    requests_per_second: 10

tzkt:
  mainnet:
    uri: https://api.tzkt.io/v1
    base_uri: https://api.tzkt.io
  
services:
  mainnet:
    mempool: https://mempool.dipdup.net/v1/graphql
  ghostnet:
    mempool: https://mempool.dipdup.net/v1/graphql
  jakartanet:
    mempool: https://mempool.dipdup.net/v1/graphql

storage:
  pg: 
    host: ${DB_HOSTNAME:-db}
    port: 5432
    user: ${POSTGRES_USER}
    dbname: ${POSTGRES_DB:-bcd}
    password: ${POSTGRES_PASSWORD}
    sslmode: disable
  timeout: 10

sentry:
  environment: production
  uri: ${SENTRY_DSN}
  front_uri: ${SENTRY_DSN_FRONT}
  debug: false

share_path: /etc/bcd

base_url: https://better-call.dev

ipfs:
  - ${SANDBOX_IPFS_GATEWAY:-http://ipfs_ipfs-node:8080}

api:
  project_name: api
  bind: ":14000"
  swagger_host: "api.better-call.dev"
  cors_enabled: false
  sentry_enabled: true
  seed_enabled: false
  page_size: ${PAGE_SIZE:-10}
  frontend:
    ga_enabled: true
    mempool_enabled: true
    sandbox_mode: false
    rpc:
      mainnet: https://rpc.tzkt.io/mainnet
      ghostnet: https://rpc.tzkt.io/ghostnet
      jakartanet: https://rpc.tzkt.io/jakartanet
  networks:
    - mainnet
    - ghostnet
    - jakartanet
  connections:
    max: 50
    idle: 10

indexer:
  project_name: indexer
  sentry_enabled: true
  skip_delegator_blocks: false
  offchain_base_url: ${OFFCHAIN_BASE_URL}
  networks:
    mainnet:
      receiver_threads: ${MAINNET_THREADS:-1}
    ghostnet:
      receiver_threads: ${TESTNET_THREADS:-1}
    jakartanet:
      receiver_threads: ${TESTNET_THREADS:-1}
  connections:
    max: 5
    idle: 5

scripts:
  aws:
    bucket_name: bcd-elastic-snapshots
    region: eu-central-1
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  networks:
    - mainnet
    - ghostnet
    - jakartanet
  connections:
    max: 5
    idle: 5
