rpc:
  mainnet:
    uri: ${MAINNET_RPC_URI:-https://rpc.tzkt.io/mainnet}
    timeout: 20
  granadanet:
    uri: ${NEXTNET_RPC_URI:-https://rpc.tzkt.io/granadanet}
    timeout: 20
  hangzhou2net:
    uri: https://rpc.tzkt.io/hangzhou2net
    timeout: 20

services:
  mainnet:
    mempool: https://mempool.dipdup.net/v1/graphql
  granadanet:
    mempool: https://mempool.staging.dipdup.net/v1/graphql
  hangzhou2net:
    mempool: https://mempool.staging.dipdup.net/v1/graphql 

storage:
  pg: "host=${DB_HOSTNAME:-db} port=5432 user=${POSTGRES_USER} dbname=indexer password=${POSTGRES_PASSWORD} sslmode=disable"
  elastic:
    - http://${ELASTIC_HOSTNAME:-elastic}:9200
    - http://${ELASTIC_HOSTNAME:-elastic}:9200
  timeout: 10

sentry:
  environment: production
  uri: ${SENTRY_DSN}
  front_uri: ${SENTRY_DSN_FRONT}
  debug: false

share_path: /etc/bcd

base_url: https://better-call.dev

ipfs:
  - ${SANDBOX_IPFS_GATEWAY:-https://ipfs.baking-bad.org}

api:
  project_name: api
  bind: ":14000"
  swagger_host: "api.better-call.dev"
  cors_enabled: false
  sentry_enabled: true
  seed_enabled: false
  page_size: ${PAGE_SIZE:-10}
  frontend:
    ga_enabled: true
    mempool_enabled: true
    sandbox_mode: false
  networks:
    - mainnet
    - granadanet
    - hangzhou2net
  connections:
    max: 50
    idle: 10

indexer:
  project_name: indexer
  sentry_enabled: true
  skip_delegator_blocks: false
  networks:
    mainnet:
    granadanet:
    hangzhou2net:
  connections:
    max: 5
    idle: 5

metrics:
  project_name: metrics
  sentry_enabled: true
  cache_aliases_seconds: 30
  connections:
    max: 20
    idle: 20

scripts:
  aws:
    bucket_name: bcd-elastic-snapshots
    region: eu-central-1
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  networks:
    - mainnet
    - granadanet
    - hangzhou2net
  connections:
    max: 5
    idle: 5
