rpc:
  sandboxnet:
    uri: ${SANDBOX_NODE_URI:-http://127.0.0.1:20000}
    timeout: 10
    requests_per_second: 10

storage:
  pg: 
    host: ${DB_HOSTNAME:-db}
    port: 5432
    user: ${POSTGRES_USER}
    dbname: ${POSTGRES_DB:-bcd}
    password: ${POSTGRES_PASSWORD}
    sslmode: disable
  timeout: 10

log_level: ${LOG_LEVEL:-info}

share_path: /etc/bcd

base_url: http://localhost:8000

api:
  project_name: api
  bind: ":14000"
  cors_enabled: true
  sentry_enabled: false
  seed_enabled: true
  page_size: ${PAGE_SIZE:-10}
  frontend:
    ga_enabled: false
    mempool_enabled: false
    sandbox_mode: true
    rpc:
      sandboxnet: ${SANDBOX_NODE_URI:-http://127.0.0.1:20000}
  networks:
    - sandboxnet

indexer:
  project_name: indexer
  sentry_enabled: false
  networks:
    sandboxnet:
      receiver_threads: 5

scripts:
  networks:
    - sandboxnet
