rpc:
  sandboxnet:
    uri: ${SANDBOX_NODE_URI}
    timeout: 10

storage:
  pg: "host=${DB_HOSTNAME:-db} port=5432 user=${POSTGRES_USER} dbname=${POSTGRES_DB:-indexer} password=${POSTGRES_PASSWORD} sslmode=disable"
  elastic:
    - http://${ELASTIC_HOSTNAME:-elastic}:9200
  timeout: 10

share_path: /etc/bcd

base_url: http://localhost:8000

ipfs:
  - ${SANDBOX_IPFS_GATEWAY}

api:
  project_name: api
  bind: ":14000"
  swagger_host: "localhost:8000"
  cors_enabled: true
  sentry_enabled: false
  seed_enabled: true
  page_size: ${PAGE_SIZE:-10}
  frontend:
    ga_enabled: false
    mempool_enabled: false
    sandbox_mode: true
    rpc:
      sandboxnet: ${SANDBOX_NODE_URI}
  seed:
    user:
      login: sandboxuser
      name: "Default User"
      avatar_url: "https://services.tzkt.io/v1/avatars/bcd"
      token: ""
    subscriptions:
      - address: tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
        network: sandboxnet
        alias: Alice
        watch_mask: 127
      - address: tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6
        network: sandboxnet
        alias: Bob
        watch_mask: 127
    aliases:
      - alias: Alice
        network: sandboxnet
        address: tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
      - alias: Bob
        network: sandboxnet
        address: tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6
    accounts:
      - private_key: "privatekey"
        public_key_hash: "publickeyhash"
        network: "sandboxnet"
  networks:
    - sandboxnet

indexer:
  project_name: indexer
  sentry_enabled: false
  skip_delegator_blocks: false
  networks:
    sandboxnet:

metrics:
  project_name: metrics
  sentry_enabled: false
  cache_aliases_seconds: 30

scripts:
  networks:
    - sandboxnet
