rpc:
  mainnet:
    uri: https://mainnet-tezos.giganode.io
    timeout: 20
  edo2net:
    uri: https://rpc.tzkt.io/edo2net
    timeout: 20
  florencenet:
    uri: https://rpc.tzkt.io/florencenobanet
    timeout: 20

storage:
  pg: "host=${DB_HOSTNAME} port=5432 user=${POSTGRES_USER} dbname=${POSTGRES_DB} password=${POSTGRES_PASSWORD} sslmode=disable"
  elastic:
    - http://${ELASTIC_HOSTNAME:-elastic}:9200
  timeout: 10

rabbitmq:
  uri: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_HOSTNAME:-mq}:5672/"
  timeout: 10

oauth:
  state: ${OAUTH_STATE_STRING}
  jwt:
    secret: ${JWT_SECRET_KEY}
    redirect_url: https://you.better-call.dev/welcome
  github:
    client_id: ${GITHUB_CLIENT_ID}
    secret: ${GITHUB_CLIENT_SECRET}
    callback_url: https://you.better-call.dev/v1/oauth/github/callback
  gitlab:
    client_id: ${GITLAB_CLIENT_ID}
    secret: ${GITLAB_CLIENT_SECRET}
    callback_url: https://you.better-call.dev/v1/oauth/gitlab/callback

sentry:
  environment: staging
  uri: ${SENTRY_DSN}
  front_uri: ${SENTRY_DSN_FRONT}
  debug: false

share_path: /etc/bcd

base_url: https://you.better-call.dev

ipfs:
  - ${SANDBOX_IPFS_GATEWAY:-https://ipfs.baking-bad.org}
  - https://cloudflare-ipfs.com
  - https://ipfs.io
  - https://dweb.link

domains:
  edo2net: KT1KP2Yy6MNkYKkHqroGBZ7KFN5NdNfnUHHv

api:
  project_name: api
  bind: ":14000"
  swagger_host: "you.better-call.dev"
  cors_enabled: false
  oauth_enabled: true
  sentry_enabled: true
  seed_enabled: false
  page_size: ${PAGE_SIZE:-10}
  frontend:
    ga_enabled: false
    mempool_enabled: true
    sandbox_mode: false
  networks:
    - mainnet
    - edo2net
    - florencenet
  pinata:
    key: ${PINATA_KEY}
    secret_key: ${PINATA_SECRET_KEY}
    timeout_seconds: 10

compiler:
  project_name: compiler
  aws:
    bucket_name: bcd-contract-sources
    region: eu-central-1
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  sentry_enabled: true
  mq:
    publisher: true
    queues:
      compilations:

indexer:
  project_name: indexer
  sentry_enabled: true
  skip_delegator_blocks: false
  mq:
    publisher: true
  networks:
    mainnet:
    edo2net:
    florencenet:

metrics:
  project_name: metrics
  sentry_enabled: true
  cache_aliases_seconds: 30
  mq:
    publisher: false
    queues:
      operations:
        lazy: true
      contracts:
        lazy: true
      bigmapdiffs:
        lazy: true

scripts:
  aws:
    bucket_name: bcd-elastic-snapshots
    region: eu-central-1
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  networks:
    - mainnet
    - edo2net
    - florencenet
  mq:
    publisher: true

graphql:
  db: "host=${DB_HOSTNAME} port=5432 user=graphql dbname=indexer password=${POSTGRES_GRAPHQL} sslmode=disable"