rpc:
    mainnet:
        uri: https://mainnet-tezos.giganode.io
        timeout: 20
    zeronet:
        uri: https://rpc.tzkt.io/zeronet
        timeout: 20
    babylonnet:
        uri: https://rpc.tzkt.io/babylonnet
        timeout: 20
    carthagenet:
        uri: https://testnet-tezos.giganode.io
        timeout: 20
    sandboxnet:
        uri: http://sandbox:8732
        timeout: 10

tzkt:
    mainnet:
        uri: https://api.tzkt.io/v1/
        timeout: 20
    zeronet:
        uri: https://api.zeronet.tzkt.io/v1/
        timeout: 20
    babylonnet:
        uri: https://api.babylon.tzkt.io/v1/
        timeout: 20
    carthagenet:
        uri: https://api.carthage.tzkt.io/v1/
        timeout: 20

share:
    path: /etc/bcd

elastic:
    uri: http://127.0.0.1:9200
    timeout: 30

rabbitmq:
    uri: "amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@127.0.0.1:5672/"
    queues:
        - operations
        - contracts
        - migrations
        - recalc

db:
    conn_string: "host=127.0.0.1 port=5432 user=${POSTGRES_USER} dbname=bcd password=${POSTGRES_PASSWORD} sslmode=disable"

aws:
    bucket_name: bcd-elastic-snapshots
    region: eu-central-1

migrations:
    networks:
        - mainnet
        - carthagenet
        - zeronet
        - babylonnet
