share:
    path: ${HOME}/.bcd

sentry:
    environment: development
    uri: ${SENTRY_DSN}
    debug: true

elastic:
    uri: http://127.0.0.1:9200
    timeout: 30

rabbitmq:
    uri: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@127.0.0.1:5672/"

indexer:
    project_name: indexer
    sentry:
        enabled: false
    networks:
        mainnet:
          boost: tzkt
        # carthagenet:
        #   boost: tzkt
        # delphinet:
        #   boost: tzkt
        # dalphanet:
