rpc:
    mainnet:
        uri: https://rpc.tzkt.io/mainnet
        timeout: 20
    delphinet:
        uri: https://rpc.tzkt.io/delphinet
        timeout: 20
    dalphanet:
        uri: https://rpc.tzkt.io/dalphanet
        timeout: 20
    carthagenet:
        uri: https://rpc.tzkt.io/carthagenet
        timeout: 20

tzkt:
    mainnet:
        uri: https://api.tzkt.io/v1/
        timeout: 20
    delphinet:
        uri: https://api.delphi.tzkt.io/v1/
        timeout: 20
    carthagenet:
        uri: https://api.carthage.tzkt.io/v1/
        timeout: 20

share:
    path: /etc/bcd

sentry:
    environment: production
    uri: ${SENTRY_DSN}
    debug: false

elastic:
    uri: http://elastic:9200
    timeout: 30

rabbitmq:
    uri: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@mq:5672/"
    publisher: true

indexer:
    project_name: indexer
    sentry:
        enabled: true
    networks:
        mainnet:
          boost: tzkt
        carthagenet:
          boost: tzkt
        delphinet:
          boost: tzkt
        dalphanet:

db:
    conn_string: "host=db port=5432 user=${POSTGRES_USER} dbname=${POSTGRES_DB} password=${POSTGRES_PASSWORD} sslmode=disable"
