rpc:
    sandboxnet:
        uri: http://sandbox:8732
        timeout: 20

metrics:
    project_name: metrics
    sentry:
        enabled: false
    queues:
        - operations
        - contracts
        - migrations
        - recalc
        - transfers
