rpc:
    mainnet:
        uri: https://mainnet-tezos.giganode.io
        timeout: 20
    delphinet:
        uri: https://rpc.tzkt.io/delphinet
        timeout: 20
    dalphanet:
        uri: https://rpc.tzkt.io/dalphanet
        timeout: 20
    carthagenet:
        uri: https://testnet-tezos.giganode.io
        timeout: 20

sentry:
    environment: production
    uri: ${SENTRY_DSN}
    debug: false

elastic:
    uri: http://elastic:9200
    timeout: 30

rabbitmq:
    uri: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@mq:5672/"

db:
    conn_string: "host=db port=5432 user=${POSTGRES_USER} dbname=${POSTGRES_DB} password=${POSTGRES_PASSWORD} sslmode=disable"

metrics:
    project_name: metrics
    sentry:
        enabled: true
    queues:
        - operations
        - contracts
        - migrations
        - recalc
        - transfers
