name: Build
on:
  push:
    branches:
      - 'master'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_BASE: ${{ github.repository }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # DB

      # - name: DB image tags & labels
      #   id: meta-db
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}-db

      # - name: DB
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: build/db/Dockerfile
      #     push: true
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
      #     tags: ${{ steps.meta-db.outputs.tags }}
      #     labels: ${{ steps.meta-db.outputs.labels }}

      # API

      - name: API image tags & labels
        id: meta-api
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}-api

      - name: API image build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/api/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}

      # Indexer

      - name: Indexer image tags & labels
        id: meta-indexer
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}-indexer

      - name: Indexer image build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/indexer/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta-indexer.outputs.tags }}
          labels: ${{ steps.meta-indexer.outputs.labels }}

      # Sandbox GUI

      - name: GUI image tags & labels
        id: meta-gui
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}-gui

      - name: GUI image build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/sandbox/Dockerfile
          build-args: |
            TAG=4.1.0
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta-gui.outputs.tags }}
          labels: ${{ steps.meta-gui.outputs.labels }}