name: Release
on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    name: Publish Github release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
    # - name: Create Sentry release
    #   uses: getsentry/action-release@v1
    #   env:
    #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    #     SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
    #     SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
    #     SENTRY_URL: ${{ secrets.SENTRY_URL }}
    #   with:
    #     environment: production
    #     version: ${{ env.RELEASE_VERSION }}

  build:
    name: Build sandbox GUI
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_BASE: ${{ github.repository }}
    steps:
      - name: GUI image tags & labels
        id: meta-gui
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}-gui

      - name: GUI image build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/sandbox/Dockerfile
          build-args: |
            TAG=4.6.2
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta-gui.outputs.tags }}
          labels: ${{ steps.meta-gui.outputs.labels }}
