on:
  push:
    branches:
      - master
name: github actions build
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --timeout=2m
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: golang tests
        env:
          GO111MODULE: on
          BCD_ENV: production
        run: |
          go mod download
          go test ./...
      - name: docker-compose test build
        run: |
          touch .env
          docker-compose build
