on: pull_request
name: Pull Request Tests 
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.28
          args: --timeout=2m
  test:
    runs-on: ubuntu-latest
    steps:
    - name: install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.x
    - name: checkout code
      uses: actions/checkout@v2
    - name: golang tests
      env:
        GO111MODULE: on
      run: |
        go mod download
        go test ./...
    - name: docker-compose test build
      run: |
        touch .env
        docker-compose -f docker-compose.yml -f docker-compose.ci.yml build
