name: Test
on:
  push:
    branches-ignore:
      - master

jobs:
  golangci:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          args: --timeout=3m
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: golang tests
        env:
          GO111MODULE: on
        run: |
          go mod download
          go test ./...
  security:
    name: CodeQL security analyzer
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'go'    
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

