on: push
name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.x
    - name: checkout code
      uses: actions/checkout@v2
    - name: golang tests
      env:
        GO111MODULE: on
      run: |
        go mod download
        go test -v ./...
    - name: docker-compose test build
      run: |
        touch .env
        docker-compose build
